## Create a list

### Data types

* float - real numbers
* int - integer numbers
* srt - string, text
* bool - boolean (True, False)

Data scientist often want to work with multiple data points. It might be not practical to store all the date in individual variables.
Instead, it is useful to store all the information in a python list.

The list can be instanced with a variable, then put an equal sign and open brakets.
See example below of a list with the names of students in a class.

In [208]:
students = ["john", "mary", "ana", "nico", "david"]

In [209]:
students

['john', 'mary', 'ana', 'nico', 'david']

A list can contain different data types. Suppose you want to include the student age to the list.

In [210]:
student_age = ["john", 20, "mary", 18, "ana", 50, "nico", 35, "david", 29]

Even better, you can create sub-lists for each student:

In [211]:
student_info = [["john", 20],
                ["mary", 18],
                ["ana", 50],
                ["nico", 35],
                ["david", 29]]

In [212]:
student_info

[['john', 20], ['mary', 18], ['ana', 50], ['nico', 35], ['david', 29]]

Check that both student_age and student_info are lists!

In [213]:
type(student_age)

list

In [214]:
type(student_info)

list

## Subsetting lists

Now that we have created lists, we need to know how to access information on the lists. We will use what is called in Python "index" do to this.

Index is the number of the element in the list. It starts with 0, since Python follows a 0-indexing structure.

In [215]:
# Accessing the first elemens of a list
student_age[0]

'john'

In [216]:
#Accessing the second element of a list
student_age[1]

20

In [217]:
# Exercise: Access the third element of a list
student_age[2]

'mary'

One can also use negative indexes, useful for accessing the elemnets of a list starting at the end.

In [218]:
# Access the last element of a list
student_age[-1]

29

**Slicing** allows you to get multiple elements from a list

In [219]:
# Have a look at the studnet_age list and guess what it will return
student_age[3:5]

[18, 'ana']

Surprised? Only the elements with index 3 and 4 were returned. The element with inde 5 is excluded.

This is how it works. [start, end]
* *start* index is inclusive
* *end* index is exclusive

Tell python to start listing at index 0

In [220]:
student_age[:4]

['john', 20, 'mary', 18]

Tell python for starting listing at index 5 until the end.

In [221]:
student_age[5:]

[50, 'nico', 35, 'david', 29]

**Operations** with list elements

One can sum the ages of John and Ana, accessing values from *student_age*

In [222]:
sum_ages = student_age[1] + student_age[5]
sum_ages

70

How to access list elements from **list contained inside a list**?

Let's say we want to access the age of John from *student_info* list

In [223]:
# To obtain Jonh's info
student_info[0]

['john', 20]

In [224]:
# To get Jonh's age
john_age = student_info[0][1]
print(john_age)

20

Exercice: Get the age of the last student in the list

In [225]:
# solution
age_last_student = student_info[-1][1]
print(age_last_student)

# other valid solutions
age_last_student = student_info[-1][-1]
print(age_last_student)

age_last_student = student_info[4][1]
print(age_last_student)

29
29
29

## Manipulating lists



*   Change elements in list
*   Add elements to list
*   Remove elements from list

### Changing list elements

In [226]:
print(student_age)

['john', 20, 'mary', 18, 'ana', 50, 'nico', 35, 'david', 29]

Suppose we found a mistake in our list *student_age* that we want to correct. The age correspondent to mary (index 3) is incorrect and we want to change it.

In [227]:
student_age[3] = 19

To check if the value is updated now, we can print the list *student_age* again.

In [228]:
print(student_age)

['john', 20, 'mary', 19, 'ana', 50, 'nico', 35, 'david', 29]

We can also change multiple elements at the same time.

In [229]:
student_age[2:4] = ["maria", 20]
print(student_age)

['john', 20, 'maria', 20, 'ana', 50, 'nico', 35, 'david', 29]

In [230]:
# However, pay attention that the following is not possible to do!!!
#student_age[4,7,9] = ["anna", "nicolau", 32]
#print(student_age)

### Adding elements to a list

Simply use the + sign.
Suppose I want to add another student information to the list.

In [231]:
student_age + ["charlotte", 37]

['john', 20, 'maria', 20, 'ana', 50, 'nico', 35, 'david', 29, 'charlotte', 37]

In [232]:
print(student_age)

['john', 20, 'maria', 20, 'ana', 50, 'nico', 35, 'david', 29]

### Deleting elements from a list

Delete the element with index x by using: del(list_name[x])

In [233]:
# Deletes the last element from a list
del(student_age[-1])

### Copying lists

In [234]:
list_a = [1,2,3]
list_b = list_a

If we try to copy lists using the = sign, x and y point to the same list. Which means that if we change an element in x, y is affected and vice versa.

In [235]:
list_a[0]=2
print(list_a)
print(list_b)

[2, 2, 3]
[2, 2, 3]

In [236]:
list_b[2]=5
print(list_a)
print(list_b)

[2, 2, 5]
[2, 2, 5]

To avoid this, we can create a new list (named *list_c* in this example) that is an independent copy of *list_a*.

In [237]:
list_c = list(list_a)

In [238]:
list_c[1] = 20
print(list_c)
print(list_a)

[2, 20, 5]
[2, 2, 5]

## Exercises

**Ex1**

In the list *student_age*:
1.   Update the age of John to be 25 instead of 20.
2.   Change the name "david" to "dave".

In [239]:
#Solutions

#1
print(student_age)
student_age[1] = 25
print(student_age)

#2
student_age[-1] = "dave"
print(student_age)

['john', 20, 'maria', 20, 'ana', 50, 'nico', 35, 'david']
['john', 25, 'maria', 20, 'ana', 50, 'nico', 35, 'david']
['john', 25, 'maria', 20, 'ana', 50, 'nico', 35, 'dave']

**Ex 2**

Use the + operator to paste the list [35, "nuno", 50] to the end of the *student_age* list.

In [254]:
# Adds elements to list
print(student_age)
student_age_1 = student_age + [35, "nuno", 50]
print(student_age_1)

['john', 35, 'dave']
['john', 35, 'dave', 35, 'nuno', 50]

**Ex 3**

Delete "dave" and his corresponding age from the list *student_age_1*.

In [255]:
# What NOT to do - common mistake alert!
#Pay attention to the indexation when using del. As soon as you remove an element from a list, the indexes of the elements that come after the deleted element all change!
print(student_age_1)
del(student_age_1[-3])
del(student_age_1[-4])
print(student_age_1)

#However, you could do:
print(student_age_1)
del(student_age_1[-4])
del(student_age_1[-3])
print(student_age_1)

'''
Note
The ; sign is used to place commands on the same line.
The code above is equivalent to:
'''

print(student_age_1)
del(student_age_1[-4]); del(student_age_1[-3])
print(student_age_1)

['john', 35, 'dave', 35, 'nuno', 50]
['john', 35, 'nuno', 50]
['john', 35, 'nuno', 50]
['nuno', 50]

In [249]:
#Solution ex3

print(student_age_1)
del(student_age_1[-4:-2])
print(student_age_1)

['john', 25, 'maria', 20, 35, 'nuno', 50]
['john', 25, 'maria', 'nuno', 50]